# @package _global_

defaults:
- _self_
- /policy: vqbet_episode_tf


critic_pretrained_policy_path: /scr/ksrini/lerobot/outputs/train/2024-09-21/02-48-40_pusht_tdmpc2_tdmpc2_episode_noise4_gaussian_std5/

training:
  critic_distillation: true
  offline_steps: 1000000

distillation:
  critic_use_advantage: true
  critic_weight: 1.0